Run in Octave 8.4.0 13 years after.
Remove superflous argument to init_robot and simplify usage.
Comment plot with erasemode because
   error: __go_line__: set: unknown line property erasemode, unable ...
I had to
	pkg load statistics (chi2inv)
	pkg load mapping    (wrapToPi)
	See #1 for screenshot.